import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {validateRadarData} from './scripts/contract.mjs';
import {convert} from './scripts/convert-tables.mjs';
import {buildRadar} from './scripts/build-radar.mjs';
import {reviewSummaries} from './scripts/review-summaries.mjs';
import {verifyProvenance} from './scripts/verify-provenance.mjs';
import {mdCells, markdownTables} from './scripts/extract_sources.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),work=fs.mkdtempSync(path.join(os.tmpdir(),'capability-radar-test-'));
let count=0;
function check(name,test){test();count++;console.log('PASS '+name);}
function command(exe,args){const r=spawnSync(exe,args,{encoding:'utf8'});if(r.error)throw r.error;return r;}
const fixture=command(process.execPath,[path.join(root,'tests/make-fixtures.mjs'),work]);assert.equal(fixture.status,0,fixture.stderr);
function extract(name){const out=path.join(work,name+'.extracted.json'),r=command(process.execPath,[path.join(root,'scripts/extract_sources.mjs'),path.join(work,name),'--out',out]);assert.equal(r.status,0,r.stderr);return JSON.parse(fs.readFileSync(out,'utf8'));}
const example=JSON.parse(fs.readFileSync(path.join(root,'assets/example.json'),'utf8'));
check('valid contract and domains',()=>assert.equal(validateRadarData(example).capabilities.length,3));
for(const [name,edit] of [['unknown status',d=>d.capabilities[0].status='在研'],['duplicate IDs',d=>d.capabilities[1].id=d.capabilities[0].id],['bad date',d=>d.date='2026-02-30'],['bad domain',d=>d.capabilities[0].group='不存在'],['bad short label',d=>d.capabilities[0].shortLabel='很长'.repeat(15)],['source ref mismatch',d=>{d.sources=[{id:'S',name:'source',sha256:'0'.repeat(64)}];}]])check(name,()=>{const d=structuredClone(example);edit(d);assert.throws(()=>validateRadarData(d));});
check('unknown extension fields retained',()=>assert.deepEqual(validateRadarData({...example,custom:{note:'保留'}}).custom,{note:'保留'}));
check('material qualifiers omitted from summary are flagged',()=>{const d=structuredClone(example);d.capabilities[0].limits='尚未产品化；仅内部使用；不能承诺泛化。';d.capabilities[0].summary='样例通过';assert.equal(reviewSummaries(d).length,3);d.capabilities[0].summary='未产品化；仅内部，泛化未承诺';assert.equal(reviewSummaries(d).length,0);});
check('summary strengthened negation receives review finding',()=>{const d=structuredClone(example);d.capabilities[0].limits='不能承诺泛化。';d.capabilities[0].summary='不能泛化';assert.ok(reviewSummaries(d).some(f=>f.type==='predicate-strength'));d.capabilities[0].summary='泛化未承诺';assert.equal(reviewSummaries(d).length,0);});
const md=extract('table.md'),converted=convert(md);
check('Markdown mapped states preserve unknown and excluded',()=>{assert.equal(converted.data.capabilities.length,3);assert.equal(converted.report.pending.length,1);assert.equal(converted.report.excluded.length,1);assert.equal(converted.data.capabilities[1].status,'确定能做到');assert.equal(converted.data.capabilities[2].status,'可能做到');assert.equal(converted.data.capabilities[0].summary,'仅样例');validateRadarData(converted.data);});
check('Markdown code fence excluded and source locators retained',()=>{assert.equal(md.sources[0].tables.length,1);assert.match(converted.data.capabilities[0].sourceRefs[0].locator,/^line:/);assert.equal(md.sources[0].sha256.length,64);});
check('source quotes and locators match; off-by-one citation rejected',()=>{assert.equal(verifyProvenance(converted.data,md).length,0);const d=structuredClone(converted.data);d.capabilities[0].sourceRefs[0].locator='line:1';assert.ok(verifyProvenance(d,md).some(f=>f.reason.includes('不匹配')));d.sources[0].sha256='f'.repeat(64);assert.ok(verifyProvenance(d,md).some(f=>f.reason.includes('hash')));});
check('escaped pipes and code spans preserved',()=>{const d=convert(extract('escaped.md'));assert.equal(d.data.capabilities[0].name,'解析 `A|B`');assert.equal(d.data.capabilities[0].limits,'A|B 格式');});
check('CSV quoted comma and record locator',()=>{const d=convert(extract('table.csv'));assert.equal(d.data.capabilities[0].name,'导入,资料');assert.equal(d.data.capabilities[0].sourceRefs[0].locator,'record:2');});
check('TSV fields',()=>assert.equal(convert(extract('table.tsv')).data.capabilities.length,1));
check('semicolon CSV dialect',()=>assert.equal(convert(extract('semicolon.csv')).data.capabilities.length,1));
check('UTF16 CSV BOM',()=>assert.equal(convert(extract('utf16.csv')).data.capabilities.length,1));
const xlsx=extract('table.xlsx');
check('XLSX hidden sheet and actual cell coordinates',()=>{const t=xlsx.sources[0].tables[0];assert.equal(t.state,'hidden');assert.equal(t.rows[1].cells[0],'A2');assert.equal(convert(xlsx).data.capabilities.length,2);});
check('formula cache and merged cells warned without execution',()=>{const t=xlsx.sources[0].tables[0];assert.equal(t.formulas[0].cachedValue,'2');assert.equal(t.formulas[0].formula,'1+1');assert.deepEqual(t.mergedRanges,['G1:H1']);assert.equal(xlsx.sources[0].warnings.length,2);});
check('DOCX text and table extracted',()=>{const s=extract('table.docx').sources[0];assert.ok(s.text.includes('能力说明'));assert.equal(s.tables[0].rows[0].values[0],'能力名称');});
check('narrative not fabricated by deterministic converter',()=>{const d=convert(extract('narrative.txt'));assert.equal(d.data.capabilities.length,0);assert.throws(()=>validateRadarData(d.data));});
check('unsupported legacy XLS explicit failure',()=>{const r=command(process.execPath,[path.join(root,'scripts/extract_sources.mjs'),path.join(work,'bad.xls'),'--out',path.join(work,'bad.json')]);assert.equal(r.status,1);assert.equal(fs.existsSync(path.join(work,'bad.json')),false);});
check('partial input failure keeps readable sources and reports failure',()=>{const out=path.join(work,'partial.json');const r=command(process.execPath,[path.join(root,'scripts/extract_sources.mjs'),path.join(work,'table.md'),path.join(work,'bad.xls'),'--out',out]);assert.equal(r.status,2);const d=JSON.parse(fs.readFileSync(out,'utf8'));assert.equal(d.sources.length,1);assert.equal(d.failures.length,1);assert.equal(convert(d).report.readFailures.length,1);});
check('conflicting source IDs recorded instead of optimistic merge',()=>{const d=convert({sources:[...md.sources,...md.sources]});assert.equal(d.data.capabilities.length,0);assert.ok(d.report.pending.length>=6);});
const input=path.join(work,'standard.json');fs.writeFileSync(input,JSON.stringify(example));
const out=path.join(work,'built'),built=buildRadar(input,out);
check('standalone HTML embeds data and canonical contract',()=>{const h=fs.readFileSync(built.files.html,'utf8');const d=JSON.parse(h.match(/<script type="application\/json" id="initial-data">([\s\S]*?)<\/script>/)[1]);assert.equal(d.capabilities.length,3);assert.ok(h.includes(validateRadarData.toString()));assert.ok(!h.includes('WDP6'));assert.ok(!/<script[^>]+src=/.test(h));});
check('build refuses overwrite and keeps files unchanged',()=>{const before=fs.readFileSync(built.files.html,'utf8');assert.throws(()=>buildRadar(input,out));assert.equal(fs.readFileSync(built.files.html,'utf8'),before);});
check('source JSON remains unchanged',()=>assert.equal(fs.readFileSync(input,'utf8'),JSON.stringify(example)));
const unsafe=structuredClone(example);unsafe.capabilities[0].proof='</script><script>throw 1</script>';const u=path.join(work,'unsafe.json');fs.writeFileSync(u,JSON.stringify(unsafe));const ub=buildRadar(u,path.join(work,'unsafe'));
check('embedded JSON escapes script closure and round trips',()=>{const h=fs.readFileSync(ub.files.html,'utf8'),d=JSON.parse(h.match(/<script type="application\/json" id="initial-data">([\s\S]*?)<\/script>/)[1]);assert.equal(d.capabilities[0].proof,unsafe.capabilities[0].proof);assert.ok(h.includes('\\u003c/script>'));});
check('STORED ZIP matches DEFLATE XLSX',()=>assert.deepEqual(extract('stored.xlsx').sources[0].tables,xlsx.sources[0].tables));
check('DEFLATE sharedStrings and rich text preserve values',()=>assert.deepEqual(extract('shared.xlsx').sources[0].tables,xlsx.sources[0].tables));
check('XLSM cells extracted with macro non-execution warning',()=>{const s=extract('table.xlsm').sources[0];assert.equal(s.tables[0].rows[1].values[2],'导入资料');assert.ok(s.warnings.includes('仅提取单元格；宏未执行。'));});
check('UTF16 big endian CSV BOM',()=>assert.equal(convert(extract('utf16be.csv')).data.capabilities.length,1));
check('JSON data extracted',()=>assert.deepEqual(extract('json.json').sources[0].data,{name:'资料',values:[1,true]}));
check('GB18030 text decoded without external dependency',()=>assert.equal(extract('gb18030.txt').sources[0].text,'中文'));
check('quoted multiline CSV records and escaped quotes preserved',()=>{const row=extract('multiline.csv').sources[0].tables[0].rows[1];assert.equal(row.locator,'record:2');assert.equal(row.values[2],'导入\n资料');assert.equal(row.values[4],'引号 "保留"');});
check('fence matching excludes nested fence markers',()=>{const text='~~~~markdown\n```\n| 伪表 | 状态 |\n|---|---|\n| A | 已具备 |\n```\n~~~~\n| 能力 | 状态 |\n|---|---|\n| B | 已具备 |';assert.equal(markdownTables(text).length,1);assert.equal(markdownTables(text)[0].rows[1].values[0],'B');});
check('multi-backtick code spans and escaped trailing pipe preserved',()=>assert.deepEqual(mdCells('| ``A`|B`` | C\\|'),['``A`|B``','C|']));
for(const [name,reason] of [['dtd.xlsx','DTD'],['encrypted.xlsx','加密'],['unsupported.xlsx','压缩方式'],['oversized.xlsx','96 MB'],['corrupted.xlsx','CRC']])check('reject '+name,()=>{const out=path.join(work,name+'.reject.json');const r=command(process.execPath,[path.join(root,'scripts/extract_sources.mjs'),path.join(work,name),'--out',out]);assert.equal(r.status,1);assert.ok(r.stderr.includes(reason),r.stderr);assert.equal(fs.existsSync(out),false);});
check('extraction refuses overwrite and preserves output',()=>{const out=path.join(work,'table.md.extracted.json'),before=fs.readFileSync(out,'utf8');const r=command(process.execPath,[path.join(root,'scripts/extract_sources.mjs'),path.join(work,'table.md'),'--out',out]);assert.equal(r.status,1);assert.equal(fs.readFileSync(out,'utf8'),before);});
console.log(JSON.stringify({status:'PASS',checks:count,scope:'确定性提取、契约、转换边界与构建；不包含 Agent 语义质量或浏览器视觉验收',workspace:work},null,2));
